import type { FutureCampaign } from "@/content/types";

export const futureCampaigns: readonly FutureCampaign[] = [
  {
    id: "sales-marketing-people",
    title: "Sales, Marketing & People",
    description: "Deepen the relationship, market, communication, and talent skills that create demand and trust.",
    topics: [
      "Advanced negotiation",
      "Relationship-based selling",
      "B2B sales",
      "Partnership development",
      "Customer acquisition",
      "Customer retention",
      "Marketing strategy",
      "Digital marketing",
      "Brand development",
      "Reputation management",
      "Market research",
      "Consumer behavior",
      "Networking",
      "Public speaking",
      "Presentation skills",
      "Business writing",
      "Contract fundamentals",
      "Vendor negotiation",
      "Hiring fundamentals",
      "Interviewing",
      "Employee onboarding",
      "Training",
      "Performance management",
      "Financial analysis",
      "Business valuation basics",
    ],
  },
  {
    id: "operator-leader",
    title: "Operator & Leader",
    description: "Build the systems, teams, controls, and management rhythms required to scale performance.",
    topics: [
      "Leadership",
      "Delegation",
      "Managing employees",
      "Managing managers",
      "Organizational design",
      "Hiring",
      "Compensation",
      "Employee development",
      "Culture",
      "Conflict",
      "Operations",
      "SOPs",
      "Quality control",
      "Customer experience",
      "Vendor management",
      "Project management",
      "Budgeting",
      "Forecasting",
      "KPIs",
      "Risk management",
      "Franchise operations",
      "Real estate operations",
      "Property management",
      "Insurance",
      "Compliance",
    ],
  },
  {
    id: "executive-leadership",
    title: "Executive Leadership",
    description: "Practice executive judgment across strategy, governance, communication, crisis, and major transitions.",
    topics: [
      "Executive leadership",
      "Strategy",
      "Executive decision making",
      "Managing managers",
      "Executive hiring",
      "Organizational structure",
      "Culture",
      "Executive communication",
      "Partnership negotiations",
      "Major customers",
      "Franchise development",
      "Real estate negotiation",
      "Commercial leases",
      "M&A",
      "Integration",
      "Due diligence",
      "Business valuation",
      "Corporate finance",
      "Capital allocation basics",
      "Board communication",
      "Compliance",
      "PR",
      "Crisis management",
      "Change management",
      "Succession",
    ],
  },
  {
    id: "vp-coo",
    title: "VP / COO of Skadra Ventures",
    description: "Operate a portfolio through leaders, governance, relationships, integration, reputation, and disciplined execution.",
    topics: [
      "Portfolio-company oversight",
      "Executive recruiting",
      "CEO / GM evaluation",
      "Governance",
      "Boards",
      "M&A integration",
      "Major negotiations",
      "Strategic partnerships",
      "Institutional relationships",
      "Corporate communications",
      "Brand / reputation",
      "Culture",
      "Executive compensation",
      "Risk",
      "Crisis leadership",
      "International business",
      "Advanced real estate operations",
      "Franchise portfolio management",
      "Succession",
      "Capital allocation",
    ],
  },
];

